### PR TITLE
adding support for xxxhdpi notification icons

### PR DESCRIPTION
**Pull request by jishnu7**
xxxhdpi app icons are supported and notifications are not.

### CODE REVIEW

**Comment by martell** [comment]
Hi @jishnu7, Sorry this wasn't looked at sooner.
I joined the dev team recently and will be dealing with native PR's in future.
Martell

**Comment by jishnu7** [comment]
Thanks Martel.

We have more changes in our repo. If you are interested in any of those,
you can cherry pick or I can send PRs.

https://github.com/hashcube/native-android/commits/hc

**Comment by jishnu7** [comment]
@martell just saw other PR comments. Will wait for the new tealeaf to be open.

**Comment by martell** [comment]
I'll make sure support for this makes it into the new repo and you can make other PR's after that if you want.

**Pull request merged**
