### PR TITLE
Move icons from drawable to mipmap

### PR DESCRIPTION
**Pull request by rampr**
Following this according to Android's best practices:

https://developer.android.com/guide/practices/screens_support.html#support

### CODE REVIEW

**Comment by rampr** [comment]
@martell @rogueSkib ^

**Comment by rogueSkib** [comment]
Hey @rampr - just curious, does this have any visible affects on native-android builds?

**Comment by jishnu7** [comment]
@rogueSkib Nothing visible. Google Play review team suggested us to make this modification.

**Comment by rampr** [comment]
@rogueSkib there would be no visible effects for native-android builds.

**Comment by rogueSkib** [comment]
Great, thanks for sharing this guys! Looks good to me 👍

**Pull request merged**
